beacon_billing.settings:
  type: config_object
  label: 'Billing settings'
  mapping:
    default_plan_id:
      type: string
      label: 'Default plan ID'
    trial_period_days:
      type: integer
      label: 'Free trial period (days)'
    alert_email:
      type: string
      label: 'Alert email address'
